### ISSUE TITLE
Update pojavlauncher section.

### ISSUE THREAD

**Issue by adex345** [TayouVR/MinecraftLauncherComparison#6]
It now supports modpacks and auto installs modloaders like fabric forge and quilt

**Comment by TayouVR** [comment]
Thank you for the report! ❤️ 
I added what I could see in launcher in https://github.com/TayouVR/MinecraftLauncherComparison/commit/a177d7d1ee0c7b83b1f4ff250ec7bcf97694dbd5

If there is anything missing or if any more features are added in the future feel free to tell me and I will update the list.
