### ISSUE TITLE
Vanilla launcher has instance support

### ISSUE THREAD

**Issue by Gaming32** [TayouVR/MinecraftLauncherComparison#7]
The vanilla launcher supports multiple instances, which can be different versions, different screen sizes, have different JVM args, and be in separate folders. They also recently added a "Quick Launch" feature that allows you to launch pinned instances with one click.

**Comment by TayouVR** [comment]
the vanilla launcher does not separate resourcepacks, mods, shaders, configs or any other things between profiles. Therefore they are not their own instances. the quick launch feature is neat, but other launchers like prism launcher have had one click launch for all instances since their inception.

**Comment by Gaming32** [comment]
The Vanilla launcher does allow these things to be separated, as I previously mentioned.

**Comment by TayouVR** [comment]
ah I overread the folder thing. That part is the only relevant information here. Downloaded the launcher to see for myself, and it looks like that is actually quite useful. I will adjust the note for that.
